# Generated by Django 2.1.1 on 2018-09-27 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pontuacao'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('enunciado', models.CharField(max_length=1000, null=True)),
                ('alternativaA', models.CharField(max_length=500, null=True)),
                ('alternativaB', models.CharField(max_length=500, null=True)),
                ('alternativaC', models.CharField(max_length=500, null=True)),
                ('alternativaD', models.CharField(max_length=500, null=True)),
                ('alternativa_certa', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('nivel', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Média'), (3, 'Difícil')], default=1)),
            ],
            options={
                'ordering': ['enunciado'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=5, null=True)),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.Academico')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.Pergunta')),
            ],
        ),
    ]
