# Generated by Django 2.1.1 on 2018-09-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='alternativaA',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativaB',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativaC',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativaD',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='enunciado',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
