# Generated by Django 2.1.1 on 2018-09-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0002_auto_20180927_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='CGU',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
